# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 10:30
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flickrid', models.CharField(db_index=True, max_length=30, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('photos', django.contrib.postgres.fields.jsonb.JSONField()),
                ('info', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
