# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-31 13:48
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flickr', '0003_auto_20170731_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='info',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
    ]
