# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-01 08:02
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flickr', '0004_auto_20170731_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='Following',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='flickr.Person', to_field='flickrid')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='flickr.Person', to_field='flickrid')),
            ],
        ),
        migrations.RemoveField(
            model_name='fav',
            name='person',
        ),
        migrations.AddField(
            model_name='fav',
            name='info',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='fav',
            name='photoid',
            field=models.CharField(db_index=True, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fav',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flickr.Person', to_field='flickrid'),
            preserve_default=False,
        ),
    ]
