# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-01 12:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flickr', '0005_auto_20170801_0802'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='following',
            unique_together=set([('follower', 'followed')]),
        ),
    ]
