# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-03 12:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flickr', '0006_auto_20170801_1210'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fav',
            unique_together=set([('user', 'photoid')]),
        ),
    ]
